version: "3"
name: adener

x-defaults: &defaults
  volumes:
    - /raid:/raid
    - ${SSH_AUTH_SOCK}:/ssh-agent
    - ${DEVROOT}:${DEVROOT}
    - ${HOME}:${HOME}
  environment:
    - SSH_AUTH_SOCK=/ssh-agent
  user: 100341:30
  init: true
  network_mode: host
  ipc: host
  stdin_open: true
  tty: true
  command: /bin/bash
  privileged: true
  shm_size: 1000000000  # 1g
  ulimits: &ulimits
    memlock: -1
    stack: 67108864
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

services:

  te-jax-dev:
    <<: *defaults
    container_name: te-jax-dev
    build:
      context: .
      cache_from:
        - ghcr.io/nvidia/jax:pax
      args:
        base: ghcr.io/nvidia/jax:pax
        pydeps: git+https://github.com/deepmind/einshape
    working_dir: ${DEVROOT}/code/te-jax-dev

  te-torch-dev:
    <<: *defaults
    container_name: te-torch-dev
    build:
      context: .
      cache_from:
        - gitlab-master.nvidia.com/dl/dgx/pytorch:master-py3-devel
      args:
        base: gitlab-master.nvidia.com/dl/dgx/pytorch:master-py3-devel
        pydeps:
    working_dir: ${DEVROOT}/code/te-torch-dev

  te-all-dev:
    <<: *defaults
    container_name: te-all-dev
    build:
      context: .
      cache_from:
        - gitlab-master.nvidia.com/dl/dgx/pytorch:master-py3-devel
      args:
        base: gitlab-master.nvidia.com/dl/dgx/pytorch:master-py3-devel
        pydeps: jax[cuda12_local],git+https://github.com/google/flax,git+https://github.com/google/praxis,git+https://github.com/deepmind/einshape
    working_dir: ${DEVROOT}/code
